### PR TITLE
Fix code quality issues note listing UI

### LINKED ISSUE #10: Fix code quality issues in note listing page UI
- [x] Remove unnecessary Blank lines.
- [x] Keep imports consistent.
- [x] Fix naming issues ( NOTES_LIST , card , day.js)
- [x] Use arrow functions instead of function keyword
- [x] Use functions that return jsx instead of creating a component for small components
- [x] Use dayjs instead of Date.

### PR DESCRIPTION
**Pull request by sayoojtmc**
Fixes #10 
@yedhink  Please review.
Made the following changes:
- [x] Remove unnecessary Blank lines.
- [x] Keep imports consistent.
- [x] Fix naming issues ( NOTES_LIST , card , day.js)
- [x] Use arrow functions instead of function keyword
- [x] Separated NoteDropDown component from Card component
- [x] Use dayjs instead of Date.

### CODE REVIEW

File: app/javascript/src/components/Notes/Card.jsx [hunk 1]
```diff
@@ -1,12 +1,17 @@
...
+import { Clock } from "neetoicons";
+import { Label, Typography, Tag, Avatar, Tooltip } from "neetoui";
 
-import { calculateCreatedAgo, getDayFromDate } from "utils/index";
+import NoteDropDown from "components/Notes/NoteDropDown";
+import {
+  calculateCreatedAgo,
+  getDateObject,
+  getDayFromDate,
+} from "utils/index";
```
Comment (yedhink) [inline app/javascript/src/components/Notes/Card.jsx:11]: I want you to put up a video and show me, how even after having an eslint rule to prevent useless `index` references, this statement got committed in your Git branch:

https://github.com/bigbinary/wheel/blob/f916e847419f0587ef4cf5cd5abb41c200188dfc/.eslint-rules/imports/enforced.js#L8

File: app/javascript/src/utils/index.js [hunk 2]
```diff
@@ -5,3 +5,4 @@ export const isPresent = R.pipe(R.either(R.isNil, R.isEmpty), R.not);
 
 export const calculateCreatedAgo = date => dayjs(date).fromNow();
 export const getDayFromDate = date => dayjs(date).format("dddd, hh:mmA");
+export const getDateObject = date => dayjs(date);
```
Comment (yedhink) [inline app/javascript/src/utils/index.js:8]: This function is pointless. It doesn't add much value from readability perspective nor from reusability perspective.

Remove this function.

**Review by yedhink — COMMENTED** [review]
@sayoojtmc

File: app/javascript/src/components/Notes/Card.jsx (hunk 1 above)
Comment (sayoojtmc) [reply app/javascript/src/components/Notes/Card.jsx:11]: Here's a loom video showing me executing eslint commands but utils/index is still present
https://www.loom.com/share/16ba6235fa36475ab8b0ec1762532a9b

Comment (yedhink) [reply app/javascript/src/components/Notes/Card.jsx:11]: Lemme check.
